# Generated by Django 4.1.13 on 2024-03-07 16:38

from django.db import migrations, models
import djongo.models.fields
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('birthDate', models.DateField()),
                ('images', djongo.models.fields.ArrayField(model_container=myapp.models.Image)),
                ('isState', models.BooleanField(default=True)),
            ],
        ),
    ]
