"""
Django settings for AppYoLo_DA_Chuyen_Nganh project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
# import cloudinary
import os
# import cloudinary.api_client
# import cloudinary.uploader
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9ymxdoo395914j!cc+7*ca(uow3x&9-afw&irqbq55pwp6wku#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

<<<<<<< HEAD
ALLOWED_HOSTS = ['34.143.251.116','10.148.0.4','kait.id.vn']
=======
ALLOWED_HOSTS = []
>>>>>>> main
#ALLOWED_HOSTS = ['.vercel.app','.now.sh','127.0.0.1','localhost']
STATICFILES_DIRS = [BASE_DIR/'static',]
STATIC_ROOT = BASE_DIR/'staticfiles'    
# Application definition


from google.oauth2 import service_account
GS_CREDENTIALS = service_account.Credentials.from_service_account_file(os.path.join(BASE_DIR,'credential.json'))


<<<<<<< HEAD
DEFAULT_FILE_STORAGE='django_blog_project.gcloud.GoogleCloudMediaFileStorage'
GS_PROJECT_ID = 'pragmatic-ruler-414605'
GS_BUCKET_NAME = 'kait_bucket_django'
=======
DEFAULT_FILE_STORAGE = "storages.backends.gcloud.GoogleCloudStorage"
GS_PROJECT_ID = 'pragmatic-ruler-414605'
GS_BUCKET_NAME = 'kait_bucket_django'
    
GS_BLOB_CHUNK_SIZE = 1024 * 256 * 40 
>>>>>>> main
MEDIA_ROOT = "media/"
UPLOAD_ROOT = 'media/uploads/'
MEDIA_URL = 'https://storage.googleapis.com/{}/'.format(GS_BUCKET_NAME)

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',
    'djongo'
    # 'cloudinary'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AppYoLo_DA_Chuyen_Nganh.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AppYoLo_DA_Chuyen_Nganh.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'CLIENT':{
            'host':'mongodb+srv://huynhdangkhoawork:AeOGIJfQgQNS2aHF@cluster0.f7l1yuy.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0',
            'name':'kaitStudy',
            'authMechanism': 'SCRAM-SHA-1',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
CSRF_TRUSTED_ORIGINS = [
    'http://34.143.251.116',
    'http://kait.id.vn'
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
STATIC_URL = "/static/"
STATICFILES_DIRS=[
    os.path.join(BASE_DIR,'static')
]
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# cloudinary.config(
#     cloud_name = "dpa8dyxil",
#     api_key="435291857494115",
#     api_secret ="uwajykGq-jlx5tzjv6sOA3gomhI",
#     secure = True
# )
